version: "3.9"

services:
   server:
     build: .
     depends_on: 
         - postgres
     ports: 
         - 4000:4000
   postgres:
      image: postgres
      ports: 
         - 8000:5432
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "aakashjka"
        POSTGRES_DB: "perntodo"
      volumes:
         - /custom/mount:/var/lib/postgresql/data \postgres

