apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: type
    pod-template-hash: 6b9b4b99f6
  name: type-service1
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: type
    pod-template-hash: 6b9b4b99f6
  type: ClusterIP
status:
  loadBalancer: {}

